### ISSUE TITLE
Clarify the synchronization packet definition for privilege mode change

### ISSUE THREAD

**Issue by Muhammad-Saadi-Abbasi** [riscv-non-isa/riscv-trace-spec#173] opened 2024-11-19 06:06 UTC
When the mret or sret instruction is executed and it changes the privilege mode then the trace encoder emits a synchronization packet. Currently, this behavior is documented only in the delta trace algorithm diagram. Can you update the Synchronization Packet definition (Sec 7.2)  to explicitly include this scenario i.e. when privilege mode changes due to mret/sret instruction then the very first instruction after privilege mode should be reported by Sync packet?

**Comment by IainCRobertson** [comment] 2024-11-19 09:37
This is a duplicate of issue #97, which is already being addressed for the next spec revision.

**Closed by IainCRobertson** 2024-11-19 09:37 UTC
